# Generated by Django 4.2.4 on 2023-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, unique=True)),
                ('project_code', models.CharField(max_length=20, unique=True)),
                ('project_type', models.CharField(default='inside', max_length=50)),
                ('project_status', models.BooleanField(db_index=True, default=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
