# Generated by Django 4.2.4 on 2023-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_info',
            field=models.TextField(default='', max_length=100),
        ),
    ]
