# Generated by Django 4.2.4 on 2023-09-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0003_alter_projectmodel_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
    ]
