# Generated by Django 4.2.4 on 2023-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0004_alter_projectmodel_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=20)),
                ('business_code', models.CharField(max_length=20, unique=True)),
                ('owner_project', models.CharField(default='inside', max_length=50)),
                ('case_count', models.CharField(default=0, max_length=20)),
                ('run_count', models.CharField(default=0, max_length=20)),
                ('skip_count', models.CharField(default=0, max_length=20)),
                ('pass_ratio', models.CharField(default=0, max_length=20)),
                ('test_report', models.CharField(default='', max_length=200)),
                ('run_log', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
