# Generated by Django 4.2.4 on 2023-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0005_businessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='business_info',
            field=models.TextField(default='', max_length=100),
        ),
    ]
