# Generated by Django 4.2.4 on 2023-09-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0006_businessmodel_business_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='owner_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='lwbtestmune.projectmodel'),
        ),
    ]
