# Generated by Django 4.2.4 on 2023-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0009_casemodel_create_time_casemodel_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='is_run',
            field=models.CharField(default='yes', max_length=20),
        ),
    ]
