# Generated by Django 4.2.4 on 2023-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0010_alter_casemodel_is_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemodel',
            name='is_run',
        ),
        migrations.AddField(
            model_name='casemodel',
            name='case_status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='method',
            field=models.CharField(default='GET', max_length=20),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='verify_type',
            field=models.CharField(default='CODE', max_length=20),
        ),
    ]
