# Generated by Django 4.2.4 on 2023-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0013_projectmodel_project_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_login_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
