# Generated by Django 4.2.4 on 2023-09-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0015_alter_projectmodel_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_url',
            new_name='project_base_url',
        ),
    ]
