# Generated by Django 4.2.4 on 2023-09-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0017_rename_project_base_url_projectmodel_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='token_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
