# Generated by Django 4.2.4 on 2023-11-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwbtestmune', '0021_casemodel_serial_num_casemodel_verify_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casemodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='serial_num',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='casemodel',
            unique_together={('owner_project', 'owner_business', 'serial_num')},
        ),
    ]
